### ISSUE TITLE
Please add to poggit

### ISSUE THREAD

**Issue by ElektroPrinz** [tim03we/Slapper-Altay#1]
can you please this add to poggit please

**Comment by tim03we** [comment]
Since this plugin does not work properly since 1.7, it has to be fixed first. After that I like to put it on poggit.

**Comment by tim03we** [comment]
Since this plugin does not work properly since 1.7, it has to be fixed first. After that I like to put it on poggit.

**Comment by ElektroPrinz** [comment]
okay thanks I need it really 😄
