### ISSUE TITLE
/slapper edit id addcommand <cmd> isn't working

### ISSUE THREAD

**Issue by SchdowNVIDIA** [tim03we/Slapper-Altay#2]
Hey thank you for porting this plugin to Altay but there is still a issue.
When i add a command like /slapper edit 1533 lobby it won't work i slap the slapper but the command isn't running.

**Comment by tim03we** [comment]
Hello, this error is already known. Nothing has been found yet how we can fix this error. Be patient, I'm looking for a solution.

**Comment by SchdowNVIDIA** [comment]
> 
> 
> Hello, this error is already known. Nothing has been found yet how we can fix this error. Be patient, I'm looking for a solution.

Okay, thank you.
